blank_issues_enabled: true
contact_links:
  - name: Employee Manager Community Support
    url: https://github.com/chrisssp/employee-manager/discussions
    about: Please ask and answer questions here.
